include:
  - project: computing/gitlab-ci-templates
    file:
      - conda.yml
      - python.yml


stages:
  - build
  - basic
  - test
  - compatibility
  - coverage
  - deploy


.parallel_python: &parallel_python
  parallel:
    matrix:
      - PY_VERSION: ["3.8", "3.9", "3.10"]


.parallel_gwtc: &parallel_gwtc
  parallel:
    matrix:
      - CATALOG: ["1", "2", "3"]


variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  XDG_CACHE_HOME: "${CI_PROJECT_DIR}/.cache"


cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip


before_script:
  - python -m pip install .[test,extras]
  - cat pesummary/.version
  - 'apt-get update -y && bash && apt-get -y install pandoc'
  - export USER=albert.einstein
  - export NCPU=`python -c "import multiprocessing; print(min(4, multiprocessing.cpu_count()))"`


.prepare_testing: &prepare_testing
  - export BASE=`pwd`
  - export PESUMMARY_REPO_DIR=${BASE}
  - export PESUMMARY_TESTING_DIR=`python -c "import pkg_resources; print(pkg_resources.resource_filename('pesummary', 'tests'))"`
  - mkdir -p _testing
  - cd _testing


.finalise_testing: &finalise_testing
  - cd ${BASE}


tarball:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/python/#.python:build
    - .python:build
  stage: build
  needs: []


conda:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/conda/#.conda:base
    - .conda:base
  stage: build
  needs: []
  script:
    - conda create --name py310 python=3.10 pip2conda
    - conda activate py310
    - pip2conda --all --output environment.txt
    - echo "-----------------"
    - cat environment.txt
    - echo "-----------------"
    - conda install --file environment.txt -c conda-forge
    - python -m pip install .


docker:
  stage: build
  image: docker:19.03.10
  variables:
    PYTHON_VERSION: "3.8"
  before_script:
    - apk update
    - apk add py3-pip
    - apk add python3
  script:
    - python3 containers/write_dockerfile.py --python ${PYTHON_VERSION}
    - docker build -f containers/Dockerfile-pesummary-python${PYTHON_VERSION/./} -t pesummary-dev/latest . --build-arg installation=./
    - docker run pesummary-dev/latest summarytest --type imports
  artifacts:
    paths:
      - "containers/Dockerfile-pesummary-python*"


executables:
  stage: basic
  image: python:3.8
  needs:
    - tarball
  script:
    - *prepare_testing
    - summarytest --type executables
    - *finalise_testing


imports:
  stage: basic
  image: python:3.8
  needs:
    - tarball
  script:
    - *prepare_testing
    - summarytest --type imports
    - *finalise_testing


style:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/python/#.python:flake8
    - .python:flake8
  stage: basic
  needs: []
  variables:
    # don't fail the pipeline because of linting issues,
    # these are presented in the code-quality box in the
    # merge_request UI
    FLAKE8_OPTIONS: "--exit-zero"


documentation:
  stage: basic
  image: python:3.8-buster
  needs:
    - tarball
  script:
    - python -m pip install .[docs]
    - 'git lfs version || ( apt-get update -y && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install git-lfs && git lfs install)'
    - ipython kernel install --user --name=python3
    - cd docs
    - make clean
    - bash build_docs.sh
  artifacts:
    paths:
      - docs/_build/html/


examples:
  stage: basic
  image: python:3.8
  needs:
    - tarball
  script:
    - *prepare_testing
    - summarytest --type examples --repository ${PESUMMARY_REPO_DIR}
    - *finalise_testing
  allow_failure: true


authors:
  stage: basic
  image: python:3.8
  needs:
    - tarball
  script:
    - curl --request POST --form "token=$CI_EXAMPLES_TRIGGER_TOKEN" --form "variables[TYPE]=authors" --form ref=master https://git.ligo.org/api/v4/projects/3386/trigger/pipeline
  only:
    refs:
      - master@lscsoft/pesummary


.python-3.8-testing:
  needs:
    - tarball
    - executables
    - imports
    - style
  image: python:3.8
  artifacts:
    paths:
      - .coverage*
      - htmlcov/
      - coverage_badge.svg


test:base:
  <<: *parallel_python
  stage: test
  image: python:$PY_VERSION
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - *prepare_testing
    - summarytest --multi_process ${NCPU} -m "not executabletest and not ligoskymaptest and not workflowtest" --type tests --coverage --output ${BASE} --pytest_config ${BASE}/pyproject.toml
    - *finalise_testing
    - mv _testing/.coverage* .
    - mv .coverage .coverage_base
  artifacts:
    paths:
      - .coverage*
      - htmlcov/
      - coverage_badge.svg


test:executables:
  extends: test:base
  script:
    - *prepare_testing
    - summarytest --multi_process ${NCPU} -m "executabletest and not ligoskymaptest and not workflowtest" --type tests --coverage --output ${BASE} --pytest_config ${BASE}/pyproject.toml
    - *finalise_testing
    - mv _testing/.coverage* .
    - mv .coverage .coverage_exe


end-to-end:core:
  <<: *parallel_python
  stage: test
  image: python:$PY_VERSION
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - *prepare_testing
    - summarytest --multi_process ${NCPU} --type workflow -k "Core or core" --pytest_config ${BASE}/pyproject.toml
    - *finalise_testing


end-to-end:gw:
  extends: end-to-end:core
  script:
    - *prepare_testing
    - summarytest --multi_process ${NCPU} --type workflow -k "GW or gw" --pytest_config ${BASE}/pyproject.toml
    - *finalise_testing


ligo_skymap:
  extends: .python-3.8-testing
  stage: compatibility
  script:
    - *prepare_testing
    - summarytest --type skymap --coverage
    - *finalise_testing
    - mv _testing/.coverage* .
    - mv .coverage .coverage_sky
  only:
    - schedule
    - pushes


lalinference_pipe:
  stage: compatibility
  image: python:3.8-buster
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - 'git lfs version || ( apt-get update -y && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install git-lfs && git lfs install)'
    - *prepare_testing
    - summarytest --type lalinference
    - *finalise_testing
  only:
    - schedule
    - pushes


bilby:
  stage: compatibility
  image: python:3.8
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - *prepare_testing
    - summarytest --type bilby
    - *finalise_testing
  only:
    - schedule
    - pushes


bilby_pipe:
  stage: compatibility
  image: python:3.8
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - *prepare_testing
    - summarytest --type bilby_pipe
    - *finalise_testing
  only:
    - schedule
    - pushes


pycbc_inference:
  stage: compatibility
  image: python:3.8
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - *prepare_testing
    - summarytest --type pycbc
    - *finalise_testing
  only:
    - schedule
    - pushes


GWTC:
  <<: *parallel_gwtc
  stage: compatibility
  image: python:3.8
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - *prepare_testing
    - summarytest --type GWTC$CATALOG
    - *finalise_testing


coverage:
  extends: .python-3.8-testing
  stage: coverage
  needs:
    - tarball
    - test:base
    - test:executables
    - ligo_skymap
  script:
    - *prepare_testing
    - *finalise_testing
    - coverage combine .coverage_base .coverage_exe .coverage_sky
    - coverage report
    - coverage html --directory ./htmlcov/
    - coverage-badge -o coverage_badge.svg -f


build_examples:
  stage: deploy
  image: python:3.8
  script:
    - curl --request POST --form "token=$CI_EXAMPLES_TRIGGER_TOKEN" --form ref=master https://git.ligo.org/api/v4/projects/3386/trigger/pipeline
  only:
    - master@lscsoft/pesummary


pages:
  stage: deploy
  image: python:3.8
  dependencies:
    - tarball
    - executables
    - imports
    - style
    - documentation
    - examples
    - test:base
    - test:executables
    - end-to-end:core
    - end-to-end:gw
    - bilby
    - bilby_pipe
    - lalinference_pipe
    - GWTC
    - coverage
  script:
    - mkdir public/
    - mv docs/_build/html/* public/
    - mv htmlcov/ public/
    - mv coverage_badge.svg public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master@lscsoft/pesummary
