stages:
  - test
  - deploy

basic:
  stage: test
  image: python:3.6
  script:
    - pip install -r requirements.txt
    - python setup.py install
    - summarypages --help
    - summaryplots --help
    - summarypublication --help
    - summaryclassification --help
    - summaryclean --help
    - summaryreview --help
    - summarycombine --help
    - summarycombine_metafiles --help
    - python -c "import pesummary"
    - python -c "import pesummary.core"
    - python -c "import pesummary.gw"
    - python -c "import pesummary.utils"
    - python -c "import pesummary.cli"

python-3.6:
  stage: test
  image: python:3.6
  script:
    - pip install -r requirements.txt
    - pip install -r optional_requirements.txt
    - pip install bilby
    - python setup.py install
    - coverage run -m pytest tests
    - coverage report
    - coverage html
    - coverage-badge -o coverage_badge.svg -f

  artifacts:
    paths:
      - htmlcov/
      - coverage_badge.svg

python-3.7:
  stage: test
  image: python:3.7
  script:
    - pip install -r requirements.txt
    - pip install -r optional_requirements.txt
    - pip install bilby
    - python setup.py install
    - pytest tests

style:
  stage: test
  image: python:3.6
  script:
    - pip install flake8
    - flake8 . 

documentation:
  stage: test
  image: python:3.6
  script:
    - pip install -r requirements.txt
    - pip install -r optional_requirements.txt
    - python setup.py install
    - cd docs
    - make clean
    - make html
  artifacts:
    paths:
      - docs/_build/html/

build_examples:
  stage: deploy
  image: python:3.6
  script:
    - curl --request POST --form "token=$CI_EXAMPLES_TRIGGER_TOKEN" --form ref=master https://git.ligo.org/api/v4/projects/3386/trigger/pipeline
  only:
    - master

release:
  stage: deploy
  image: python:3.6
  script:
    - curl --request POST --form "variables[REPO]=pesummary" --form ref=master --form "token=$CI_RELEASE_TRIGGER_TOKEN" https://git.ligo.org/api/v4/projects/4737/trigger/pipeline
  only:
    - master
    - web

pages:
  stage: deploy
  dependencies:
    - python-3.6
    - documentation
  script:
    - mkdir public/
    - mv htmlcov/ public/
    - mv /builds/lscsoft/pesummary/coverage_badge.svg public/
    - mv docs/_build/html/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
