stages:
  - build
  - basic
  - test
  - workflow
  - consequences
  - deploy


variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip


before_script:
  - pip install -r requirements.txt
  - pip install -r optional_requirements.txt
  - pip install bilby
  - export USER=albert.einstein

.core_workflow: &core_workflow
  stage: workflow
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - pip install pesummary-*.tar.*
    - BASE=`pwd`
    - mkdir _testing
    - cd _testing
    - summarytest --type workflow -k "Core or core" --pytest_config ${BASE}/setup.cfg


.gw_workflow: &gw_workflow
  stage: workflow
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - pip install pesummary-*.tar.*
    - BASE=`pwd`
    - mkdir _testing
    - cd _testing
    - summarytest --type workflow -k "GW or gw" --pytest_config ${BASE}/setup.cfg


tarball:
  stage: build
  image: python
  script:
    - python setup.py sdist --dist-dir .
    - export PESUMMARY_TESTING_DIR=`python -c "import pkg_resources; print(pkg_resources.resource_filename('pesummary', 'tests'))"`
  artifacts:
    paths:
      - "pesummary-*.tar.*"


wheel:
  stage: build
  image: python
  script:
    - python setup.py bdist_wheel


conda:
  stage: build
  image: igwn/base:conda
  before_script:
    - ''
  script:
    - conda create --name py37 python==3.7
    - . /opt/conda/etc/profile.d/conda.sh
    - conda activate py37
    - conda install --file conda_requirements.txt -c conda-forge
    - python setup.py install
    - conda deactivate
  allow_failure: true


executables:
  stage: basic
  image: python:3.6
  needs:
    - tarball
  script:
    - pip install pesummary-*.tar.*
    - mkdir _testing
    - cd _testing
    - summarytest --type executables


imports:
  stage: basic
  image: python:3.6
  needs:
    - tarball
  script:
    - pip install pesummary-*.tar.*
    - pip install pycbc
    - mkdir _testing
    - cd _testing
    - summarytest --type imports


style:
  stage: basic
  image: python:3.6
  needs:
    - tarball
  before_script:
    - ""
  script:
    - pip install flake8
    - flake8 .


documentation:
  stage: basic
  image: python:3.6
  needs:
    - tarball
  script:
    - pip install pesummary-*.tar.*
    - cd docs
    - make clean
    - bash build_docs.sh
  artifacts:
    paths:
      - docs/_build/html/


authors:
  stage: basic
  image: python:3.6
  needs:
    - tarball
  script:
    - curl --request POST --form "token=$CI_EXAMPLES_TRIGGER_TOKEN" --form "variables[TYPE]=authors" --form ref=master https://git.ligo.org/api/v4/projects/3386/trigger/pipeline
  only:
    refs:
      - master@lscsoft/pesummary


python-3.6:
  stage: test
  image: python:3.6
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - pip install pesummary-*.tar.*
    - pip install pycbc
    - BASE=`pwd`
    - mkdir _testing
    - cd _testing
    - export PESUMMARY_TESTING_DIR=`python -c "import pkg_resources; print(pkg_resources.resource_filename('pesummary', 'tests'))"`
    - summarytest --type tests --ignore ${PESUMMARY_TESTING_DIR}/workflow_test.py ${PESUMMARY_TESTING_DIR}/ligo_skymap_test.py --pytest_config ${BASE}/setup.cfg
    - cd ${BASE}


python-3.7:
  stage: test
  image: python:3.7
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - pip install pesummary-*.tar.*
    - pip install pycbc
    - BASE=`pwd`
    - mkdir _testing
    - cd _testing
    - export PESUMMARY_TESTING_DIR=`python -c "import pkg_resources; print(pkg_resources.resource_filename('pesummary', 'tests'))"`
    - summarytest --type tests --output ${BASE} --ignore ${PESUMMARY_TESTING_DIR}/workflow_test.py ${PESUMMARY_TESTING_DIR}/ligo_skymap_test.py --coverage --pytest_config ${BASE}/setup.cfg
    - cd ${BASE}
  artifacts:
    paths:
      - htmlcov/
      - coverage_badge.svg



python-3.8:
  stage: test
  image: python:3.8
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - pip install pesummary-*.tar.*
    - BASE=`pwd`
    - mkdir _testing
    - cd _testing
    - export PESUMMARY_TESTING_DIR=`python -c "import pkg_resources; print(pkg_resources.resource_filename('pesummary', 'tests'))"`
    - summarytest --pytest_config ${BASE}/setup.cfg --type tests --ignore ${PESUMMARY_TESTING_DIR}/workflow_test.py ${PESUMMARY_TESTING_DIR}/ligo_skymap_test.py ${PESUMMARY_TESTING_DIR}/conversion_test.py


core-workflow-3.6:
  <<: *core_workflow
  image: python:3.6


core-workflow-3.7:
  <<: *core_workflow
  image: python:3.7


core-workflow-3.8:
  <<: *core_workflow
  image: python:3.8


gw-workflow-3.6:
  <<: *gw_workflow
  image: python:3.6


gw-workflow-3.7:
  <<: *gw_workflow
  image: python:3.7


gw-workflow-3.8:
  <<: *gw_workflow
  image: python:3.8


ligo_skymap:
  stage: consequences
  image: python:3.6
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - pip install pesummary-*.tar.*
    - mkdir _testing
    - cd _testing
    - summarytest --type skymap
  only:
    - schedule
    - pushes


lalinference:
  stage: consequences
  image: python:3.6
  needs:
    - tarball
    - executables
    - imports
    - style
  before_script:
    - 'git lfs version || ( apt-get update -y && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install git-lfs && git lfs install)'
  script:
    - pip install pesummary-*.tar.*
    - mkdir _testing
    - cd _testing
    - summarytest --type lalinference
  only:
    - schedule
    - pushes

##bilby:
##  stage: consequences
##  image: python:3.6
##  needs:
##    - tarball
##    - executables
##    - imports
##    - style
##  script:
##    - pip install pesummary-*.tar.*
##    - summarytest --type bilby
##  only:
##    - schedule
##    - pushes


GW190412:
  stage: consequences
  image: python:3.6
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - pip install pesummary-*.tar.*
    - mkdir _testing
    - cd _testing
    - summarytest --type GW190412
  only:
    - schedule
    - pushes


GW190425:
  stage: consequences
  image: python:3.6
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - pip install pesummary-*.tar.*
    - mkdir _testing
    - cd _testing
    - summarytest --type GW190425
  only:
    - schedule
    - pushes


GWTC1:
  stage: consequences
  image: python:3.6
  needs:
    - tarball
    - executables
    - imports
    - style
  script:
    - pip install pesummary-*.tar.*
    - mkdir _testing
    - cd _testing
    - summarytest --type GWTC1


build_examples:
  stage: deploy
  image: python:3.6
  script:
    - curl --request POST --form "token=$CI_EXAMPLES_TRIGGER_TOKEN" --form ref=master https://git.ligo.org/api/v4/projects/3386/trigger/pipeline
  only:
    - master@lscsoft/pesummary


release:
  stage: deploy
  image: python:3.6
  script:
    - curl --request POST --form "variables[REPO]=pesummary" --form ref=master --form "token=$CI_RELEASE_TRIGGER_TOKEN" https://git.ligo.org/api/v4/projects/4737/trigger/pipeline
  only:
    refs:
      - master@lscsoft/pesummary
    variables:
      - $CI_COMMIT_MESSAGE =~ /Releasing version/


pages:
  stage: deploy
  image: python:3.6
  dependencies:
    - tarball
    - executables
    - imports
    - style
    - documentation
    - python-3.6
    - python-3.7
    - python-3.8
    - core-workflow-3.6
    - core-workflow-3.7
    - core-workflow-3.8
    - gw-workflow-3.6
    - gw-workflow-3.7
    - gw-workflow-3.8
    ##- bilby
    - lalinference
    - GW190412
    - GW190425
  script:
    - mkdir public/
    - mv htmlcov/ public/
    - mv /builds/lscsoft/pesummary/coverage_badge.svg public/
    - mv docs/_build/html/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master@lscsoft/pesummary
