stages:
  - test
  - deploy

python-3:
  stage: test
  image: python:3.6
  script:
    - pip install -r optional_requirements.txt
    - python setup.py install
    - coverage run -m pytest tests
    - coverage report
    - coverage html
    - coverage-badge -o coverage_badge.svg -f

  artifacts:
    paths:
      - htmlcov/
      - coverage_badge.svg

documentation:
  stage: test
  image: python:3.6
  script:
    - apt-get -y install graphviz
    - pip install -r optional_requirements.txt
    - python setup.py install
    - cd docs
    - make clean
    - make html
  artifacts:
    paths:
      - docs/_build/html/

pages:
  stage: deploy
  dependencies:
    - python-3
  script:
    - mkdir public/
    - mv htmlcov/ public/
    - mv /builds/charlie.hoy/pesummary/coverage_badge.svg public/
    - mv docs/_build/html/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
