stages:
  - test
  - workflow
  - consequences
  - deploy

.pesummary_install: &pesummary_install |
  pip install -r requirements.txt
  pip install -r optional_requirements.txt
  pip install -r testing_requirements.txt
  pip install bilby
  python setup.py sdist
  pip install dist/*.tar.gz

executables:
  stage: test
  image: python:3.6
  script:
    - *pesummary_install
    - bash ci/test.sh --type executables

imports:
  stage: test
  image: python:3.6
  script:
    - *pesummary_install
    - bash ci/test.sh --type imports

python-3.6:
  stage: test
  image: python:3.6
  script:
    - export USER=albert.einstein
    - *pesummary_install
    - bash ci/test.sh --type tests --ignore tests/workflow_test.py --ignore tests/ligo_skymap_test.py --coverage

  artifacts:
    paths:
      - pesummary/htmlcov/
      - pesummary/coverage_badge.svg

python-3.7:
  stage: test
  image: python:3.7
  script:
    - export USER=albert.einstein
    - *pesummary_install
    - bash ci/test.sh --type tests --ignore tests/workflow_test.py --ignore tests/ligo_skymap_test.py

style:
  stage: test
  image: python:3.6
  script:
    - pip install flake8
    - bash ci/test.sh --type style

documentation:
  stage: test
  image: python:3.6
  before_script:
    - 'git lfs version || ( apt-get update -y && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install git-lfs && git lfs install)'
  script:
    - *pesummary_install
    - cd docs
    - make clean
    - bash build_docs.sh
  artifacts:
    paths:
      - docs/_build/html/

python3.6-core:
  stage: workflow
  dependencies:
    - python-3.6
    - style
    - executables
    - imports
  image: python:3.6
  script:
    - *pesummary_install
    - bash ci/test.sh --type workflow -k "Core or core"

python3.7-core:
  stage: workflow
  dependencies:
    - python-3.7
    - style
    - executables
    - imports
  image: python:3.7
  script:
    - *pesummary_install
    - bash ci/test.sh --type workflow -k "Core or core"

python3.6-gw:
  stage: workflow
  dependencies:
    - python-3.6
    - style
    - executables
    - imports
  image: python:3.6
  script:
    - *pesummary_install
    - bash ci/test.sh --type workflow -k "GW or gw"

python3.7-gw:
  stage: workflow
  dependencies:
    - python-3.7
    - style
    - executables
    - imports
  image: python:3.7
  script:
    - *pesummary_install
    - bash ci/test.sh --type workflow -k "GW or gw"

ligo_skymap:
  stage: consequences
  image: python:3.6
  script:
    - *pesummary_install
    - bash ci/test.sh --type skymap
  only:
    - schedule
    - pushes

lalinference:
  stage: consequences
  image: python:3.6
  before_script:
    - 'git lfs version || ( apt-get update -y && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install git-lfs && git lfs install)'
  script:
    - *pesummary_install
    - bash ci/test.sh --type lalinference
  only:
    - schedule
    - pushes

##bilby:
##  stage: consequences
##  image: python:3.6
##  script:
##    - *pesummary_install
##    - bash ci/test.sh --type bilby
##  only:
##    - schedule
##    - pushes

GW190412:
  stage: consequences
  image: python:3.6
  script:
    - *pesummary_install
    - bash ci/test.sh --type GW190412
  only:
    - schedule
    - pushes

GW190425:
  stage: consequences
  image: python:3.6
  script:
    - *pesummary_install
    - bash ci/test.sh --type GW190425
  only:
    - schedule
    - pushes

GWTC1:
  stage: consequences
  image: python:3.6
  script:
    - *pesummary_install
    - bash ci/test.sh --type GWTC1

build_examples:
  stage: deploy
  image: python:3.6
  script:
    - curl --request POST --form "token=$CI_EXAMPLES_TRIGGER_TOKEN" --form ref=master https://git.ligo.org/api/v4/projects/3386/trigger/pipeline
  only:
    - master@lscsoft/pesummary

release:
  stage: deploy
  image: python:3.6
  script:
    - curl --request POST --form "variables[REPO]=pesummary" --form ref=master --form "token=$CI_RELEASE_TRIGGER_TOKEN" https://git.ligo.org/api/v4/projects/4737/trigger/pipeline
  only:
    refs:
      - master@lscsoft/pesummary
    variables:
      - $CI_COMMIT_MESSAGE =~ /Releasing version/

pages:
  stage: deploy
  dependencies:
    - python-3.6
    - documentation
    - python3.6-core
    - python3.6-gw
    ##- bilby
    - lalinference
  script:
    - mkdir public/
    - mv pesummary/htmlcov/ public/
    - mv /builds/lscsoft/pesummary/pesummary/coverage_badge.svg public/
    - mv docs/_build/html/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master@lscsoft/pesummary
